import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_KR } from 'next/font/google'
import LoginContextStateProvider from "@/context/LoginContextStateProvider";
import LoginMockProvider from "@/context/LoginMockProvider";
import AccountStateProvider from "@/context/AccountStateProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const notoSansKR = Noto_Sans_KR({
  weight: ['500'],
  subsets: ['latin']
})

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${notoSansKR.className}`}
    >
      <body suppressHydrationWarning>
        <LoginContextStateProvider>
          <LoginMockProvider>
            <AccountStateProvider>
              {children}
            </AccountStateProvider>
          </LoginMockProvider>
        </LoginContextStateProvider>
      </body>
    </html>
  );
}
